[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.6.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pymicro_vad"
dynamic = ["version"]
authors = [
    {name = "Michael Hansen", email = "mike@rhasspy.org"},
]
description = "Self-contained voice activity detector"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
"Homepage" = "https://github.com/rhasspy/pymicro-vad"
"Bug Tracker" = "https://github.com/rhasspy/pymicro-vad/issues"
