---
name: wheels

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: "Wheels: Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: venv
        run: |
          python -m venv .venv
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\pip.exe install --upgrade pip; else .venv/bin/pip install --upgrade pip; fi
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\pip.exe install build; else .venv/bin/pip install build; fi
      - name: build
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\python.exe -m build --wheel; else .venv/bin/python -m build --wheel; fi
      - name: install
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\pip.exe install --no-index -f dist/ pymicro-vad; else .venv/bin/pip install --no-index -f dist/ pymicro-vad; fi
      - name: test
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\pip.exe install pytest; else pip install pytest; fi
          if [ ${{ matrix.os }} == 'windows-latest' ]; then .venv\Scripts\pytest.exe -vv tests; else pytest -vv tests; fi
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: package
          path: dist/*.whl
          overwrite: true
          include-hidden-files: false
          compression-level: 6
